// Service for making API calls to the backend R server
import { executeRCode as webRExecuteCode } from './webr';
import { apiKeyStorage } from './utils';

interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: string;
}

class ApiService {
  private baseUrl: string;
  
  constructor() {
    // In a real implementation, this would be environment-dependent
    this.baseUrl = 'https://api.example.com/r-server';
  }
  
  setApiKey(key: string) {
    apiKeyStorage.setOpenAIApiKey(key);
  }
  
  getApiKey(): string | null {
    return apiKeyStorage.getOpenAIApiKey();
  }
  
  setTemperature(temp: number) {
    apiKeyStorage.setTemperature(temp);
  }
  
  getTemperature(): number {
    return apiKeyStorage.getTemperature();
  }
  
  private async fetchWithAuth(endpoint: string, options: RequestInit = {}): Promise<Response> {
    const headers = {
      'Content-Type': 'application/json',
      ...(this.getApiKey() ? { 'Authorization': `Bearer ${this.getApiKey()}` } : {}),
      ...(options.headers || {})
    };
    
    return fetch(`${this.baseUrl}${endpoint}`, {
      ...options,
      headers
    });
  }
  
  async executeRCode(code: string, data?: any): Promise<ApiResponse> {
    try {
      console.log('Executing R code with WebR:', code);
      
      // Extract dataset name and uploaded data
      let datasetName = null;
      let uploadedData = null;
      
      if (data) {
        if (typeof data === 'string') {
          datasetName = data;
        } else {
          uploadedData = data;
        }
      }
      
      // Execute the code using WebR
      const result = await webRExecuteCode(code, datasetName, uploadedData);
      
      if (result.success) {
        return {
          success: true,
          data: {
            result: result.output || 'R code executed successfully',
            plot: result.plot || null,
            output: result.output || ''
          }
        };
      } else {
        return {
          success: false,
          error: result.error || 'Error executing R code'
        };
      }
    } catch (error) {
      console.error('Error executing R code:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }
  
  async generateSyntheticText(prompt: string): Promise<ApiResponse<string>> {
    const apiKey = this.getApiKey();
    if (!apiKey) {
      return {
        success: false,
        error: 'API key not set. Please add your API key in Settings.'
      };
    }
    
    try {
      // In a real implementation, this would call an AI API
      console.log('Generating synthetic text for prompt:', prompt);
      
      // Simulate a response
      return {
        success: true,
        data: `This is a synthetic text response to: "${prompt}". In a real implementation, this would be generated by an AI model.`
      };
    } catch (error) {
      console.error('Error generating synthetic text:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }
  
  async generateSyntheticImage(prompt: string): Promise<ApiResponse<string>> {
    const apiKey = this.getApiKey();
    if (!apiKey) {
      return {
        success: false,
        error: 'API key not set. Please add your API key in Settings.'
      };
    }
    
    try {
      // In a real implementation, this would call an AI API
      console.log('Generating synthetic image for prompt:', prompt);
      
      // Simulate a response with a placeholder image
      return {
        success: true,
        data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='
      };
    } catch (error) {
      console.error('Error generating synthetic image:', error);
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error'
      };
    }
  }
}

// Create and export a singleton instance
const apiService = new ApiService();
export default apiService;
