
import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import CodeBlock from '../CodeBlock';

interface EdaTabProps {
  selectedDataset: string | null;
  uploadedData: any | null;
}

const EdaTab: React.FC<EdaTabProps> = ({ selectedDataset, uploadedData }) => {
  const [activeTab, setActiveTab] = useState('basic');
  
  // Example output for demonstration
  const dataSummary = `
> summary(df)
      rating        complaints     privileges       learning     
 Min.   :43.00   Min.   :51.0   Min.   :30.00   Min.   :39.00  
 1st Qu.:56.25   1st Qu.:59.5   1st Qu.:44.00   1st Qu.:45.75  
 Median :64.00   Median :64.5   Median :49.50   Median :53.50  
 Mean   :63.00   Mean   :66.6   Mean   :50.80   Mean   :53.40  
 3rd Qu.:71.25   3rd Qu.:73.5   3rd Qu.:55.50   3rd Qu.:61.50  
 Max.   :81.00   Max.   :82.0   Max.   :72.00   Max.   :69.00 
      raises          critical        advance     
 Min.   :54.00   Min.   :49.00   Min.   :31.00  
 1st Qu.:58.50   1st Qu.:69.00   1st Qu.:35.00  
 Median :63.00   Median :80.00   Median :41.00  
 Mean   :64.80   Mean   :76.40   Mean   :40.40  
 3rd Qu.:70.25   3rd Qu.:84.00   3rd Qu.:46.00  
 Max.   :76.00   Max.   :92.00   Max.   :48.00
`;

  return (
    <div className="container mx-auto py-6">
      <Card className="mb-6">
        <CardHeader>
          <CardTitle className="text-lg">
            Exploratory Data Analysis: {selectedDataset || (uploadedData?.name || 'No dataset selected')}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
            <TabsList className="w-full grid grid-cols-1 md:grid-cols-6 lg:grid-cols-6">
              <TabsTrigger value="basic">Basic</TabsTrigger>
              <TabsTrigger value="summary">Summary</TabsTrigger>
              <TabsTrigger value="table1">Table 1</TabsTrigger>
              <TabsTrigger value="categorical">Categorical</TabsTrigger>
              <TabsTrigger value="numerical">Numerical</TabsTrigger>
              <TabsTrigger value="correlation">Correlation</TabsTrigger>
            </TabsList>
            
            <TabsContent value="basic" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Basic Data Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <CodeBlock code={dataSummary} language="r" />
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="summary" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Detailed Summary</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>Generated by the summarytools package using the command: summarytools::dfSummary(df).</p>
                  <div className="mt-4 border rounded p-4 bg-gray-50">
                    <p className="text-center text-muted-foreground">Detailed summary would be displayed here</p>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="table1" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Table One</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>
                    Generated by the CreateTableOne() function in the 
                    <a href="https://cran.r-project.org/web/packages/tableone/vignettes/introduction.html" target="_blank" rel="noreferrer" className="text-socr-blue hover:underline ml-1">
                      tableone
                    </a> 
                    package.
                  </p>
                  <div className="mt-4 border rounded p-4 bg-gray-50">
                    <p className="text-center text-muted-foreground">Table One would be displayed here</p>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="categorical" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Categorical Variables</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>
                    Categorical plots generated by 'plot_bar()' in the package 
                    <a href="https://cran.r-project.org/web/packages/DataExplorer/vignettes/dataexplorer-intro.html" target="_blank" rel="noreferrer" className="text-socr-blue hover:underline ml-1">
                      DataExplorer
                    </a>.
                  </p>
                  <div className="mt-4 border rounded p-4 bg-gray-50 flex justify-center">
                    <img 
                      src="https://mdn.github.io/dom-examples/canvas/pixel-manipulation/bicycle.png" 
                      alt="Categorical variables plot" 
                      className="max-w-full h-auto"
                    />
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="numerical" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Numerical Variables</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>
                    Quantile-quantile plots, using 'plot_qq()' in package 
                    <a href="https://cran.r-project.org/web/packages/DataExplorer/vignettes/dataexplorer-intro.html" target="_blank" rel="noreferrer" className="text-socr-blue hover:underline ml-1">
                      DataExplorer
                    </a>.
                  </p>
                  <div className="mt-4 border rounded p-4 bg-gray-50 flex justify-center">
                    <img 
                      src="https://mdn.github.io/dom-examples/canvas/pixel-manipulation/bicycle.png" 
                      alt="QQ plot" 
                      className="max-w-full h-auto"
                    />
                  </div>
                  <p className="mt-4">
                    Histogram plots of several variables using 'plot_histogram()' in package 
                    <a href="https://cran.r-project.org/web/packages/DataExplorer/vignettes/dataexplorer-intro.html" target="_blank" rel="noreferrer" className="text-socr-blue hover:underline ml-1">
                      DataExplorer
                    </a>.
                  </p>
                  <div className="mt-4 border rounded p-4 bg-gray-50 flex justify-center">
                    <img 
                      src="https://mdn.github.io/dom-examples/canvas/pixel-manipulation/bicycle.png" 
                      alt="Histogram plot" 
                      className="max-w-full h-auto"
                    />
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
            
            <TabsContent value="correlation" className="space-y-4">
              <Card>
                <CardHeader>
                  <CardTitle className="text-sm">Correlation Map</CardTitle>
                </CardHeader>
                <CardContent>
                  <p>
                    Correlation plot using 'corr_plot()' in package 
                    <a href="https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html" target="_blank" rel="noreferrer" className="text-socr-blue hover:underline ml-1">
                      corrplot
                    </a>.
                  </p>
                  <div className="mt-4 border rounded p-4 bg-gray-50 flex justify-center">
                    <img 
                      src="https://mdn.github.io/dom-examples/canvas/pixel-manipulation/bicycle.png" 
                      alt="Correlation map" 
                      className="max-w-full h-auto"
                    />
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  );
};

export default EdaTab;
